version: '3'
services:
  swift-base:
    build:
      context: ./
    image: swift_base
    cap_add:
     - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
  swift:
    build:
      context: ./swift
      dockerfile: Dockerfile
    depends_on:
      - swift-base
    cap_add:
     - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    
#    build:
#      context: ./swift
#    image: swift_base
#    depends_on:
#     - swift_dep
#    cap_add:
#     - SYS_PTRACE
#    security_opt:
#      - seccomp:unconfined
#
#  swift_dep:
#    build:
#      context: .
#    image: swift_dep
#    cap_add:
#     - SYS_PTRACE
#    security_opt:
#      - seccomp:unconfined
